### ISSUE TITLE
Disable "esc" close

### ISSUE THREAD

**Issue by lz100** [JohnCoene/pushbar#2]
I noticed you can press `esc` to close the pushbar. Is there a way to disable this?

**Comment by lz100** [comment]
Since your keyup listener is an anonymous function,  can't really remove the listener by the name. 

I am watching the pushbar open event on server and replace the method by `shinyjs::runjs('pushbar.__proto__.handleKeyEvent = function(){return false};')`. It works, but is not a proper way. Hope we can have an 'official' way as  an option in R function.

**Comment by lz100** [comment]
submitted a pull request  #3  to add this option.

**Comment by JohnCoene** [comment]
Thank for the PR
